name: SimpleNickCommand
version: 1.0
api: 3.0.0
main: Cmd\Main
author: TheOriginDeveloppement
website: https://github.com/TheOriginDeveloppement

commands:
  nick:
    description: Change your nickname